export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  ADMIN = 'ADMIN',
  OPERATOR = 'OPERATOR',
  EXECUTOR = 'EXECUTOR',
  MANAGER = 'MANAGER',
  LEADER = 'LEADER',
  CITIZEN = 'CITIZEN',
}

export enum AppealStatus {
  NEW = 'NEW',
  AI_ANALYZING = 'AI_ANALYZING',
  OPERATOR_REVIEW = 'OPERATOR_REVIEW',
  ASSIGNED = 'ASSIGNED',
  ACCEPTED = 'ACCEPTED',
  IN_PROGRESS = 'IN_PROGRESS',
  WAITING_CITIZEN_INFO = 'WAITING_CITIZEN_INFO',
  WAITING_EVIDENCE = 'WAITING_EVIDENCE',
  COMPLETED = 'COMPLETED',
  REJECTED = 'REJECTED',
  REOPENED = 'REOPENED',
  OVERDUE = 'OVERDUE',
  CLOSED = 'CLOSED',
}

export enum AppealPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum AppealSource {
  WEB = 'WEB',
  TELEGRAM = 'TELEGRAM',
  MOBILE = 'MOBILE',
  OPERATOR = 'OPERATOR',
  QR = 'QR',
}

export enum OrganizationType {
  HOKIMLIK = 'HOKIMLIK',
  KOMMUNAL = 'KOMMUNAL',
  BOSHQARMA = 'BOSHQARMA',
  AGENTLIK = 'AGENTLIK',
}

export enum NotificationType {
  APPEAL_CREATED = 'APPEAL_CREATED',
  AI_READY = 'AI_READY',
  ASSIGNED = 'ASSIGNED',
  STATUS_CHANGED = 'STATUS_CHANGED',
  DEADLINE_REMINDER = 'DEADLINE_REMINDER',
  OVERDUE_ALERT = 'OVERDUE_ALERT',
  COMMENT = 'COMMENT',
  SYSTEM = 'SYSTEM',
}

export enum ReportType {
  DAILY = 'DAILY',
  WEEKLY = 'WEEKLY',
  MONTHLY = 'MONTHLY',
}
